### ISSUE TITLE
Creditcard problem in IE11/Edge in payment.js with serializeArray

### ISSUE THREAD

**Issue by roms981** [wirecard/woocommerce-wcs#43]
**Problem:** Credit card payment with Wirecard Checkout Seamless not working; Javascript error in payment.js
**affected browsers:** IE/11 and Edge; 

Steps to reproduce:
1. Checkout with Wirecard Checkout Seamless
2. Choose Payment method: Credit card 
3. Enter CC data (CC Holder, Number, Valid until, ..)
4. Proceed to payment
5. Javascript error in file payment.js in L165:

`payment_information = {
L165:                    pan: this.get_data(type + 'cardnumber').replace(/\s/g, ''),
L166:                   expirationMonth: this.get_data(type + 'expirationMonth'),
L167                    expirationYear: this.get_data(type + 'expirationYear')
                };`

**pan:  this.get_data() returns error -   replace() not working on Object**

But the issue is is rather the function **serializeArray()**  in payment.js L55:

`var serialized_array = $(this).find('input:checked').parent().find('fieldset').serializeArray();`

IE is not able to serialize the CC input fields, and thus not able to set the required payment_information.

**See also:**
https://stackoverflow.com/questions/36457855/jquery-2-2-serializearray-working-in-firefox-chrome-but-not-ie11
**Demo:** https://jsfiddle.net/xu8LpmLr/5/

**Comment by rinnhofer** [comment]
Hello,
thank you for your contribution. We will look into this issue as soon as possible.

Kind regards

**Comment by tomazpu** [comment]
Hello,
the issue is solved in the new release. Thank you for your input.
