### ISSUE TITLE
Error message - CCARD expiration date wording

### ISSUE THREAD

**Issue by roms981** [wirecard/woocommerce-wcs#44]
Some users are inclined to write their expiration date as they see it on the credit card ( MM / YY).
This leads to an error, because the required format is MM-YYYY. 

```
{
	"error": [
		{
			"errorCode": 18116,
			"message": "Expiration date is invalid.",
			"consumerMessage": "Ablaufdatum ist ung&#252;ltig."
		},
		{
			"errorCode": 16116,
			"message": "Expiration date is invalid.",
			"consumerMessage": "Ablaufdatum hat ein ung&#252;ltiges Format."
		}
	],
	"errors": 2
}

```
While this is not a problem, the wording for entering an wrong expiration date (i.e., 11/18)  can be confusing to some customers, since it does not clearly state the desired formatting (MM-YYYY).

Is it possible to include the required format in the the error message?

**Comment by rinnhofer** [comment]
Hello,
we will look into the validation of credit card forms together with [Creditcard problem in IE11/Edge in payment.js with serializeArray #43](https://github.com/wirecard/woocommerce-wcs/issues/43)
as soon as possible

Kind regards

**Comment by tomazpu** [comment]
Hello,

the error message comes from server and not from the plugin. On the input mask it is clearly displayed with placeholders that the input format for the expiration date should be MM/YYYY. Thank you for your input.

Best regards
