### ISSUE TITLE
Wrong usage site_url() instead of home_url()

### ISSUE THREAD

**Issue by starflower** [wirecard/woocommerce-wcs#69]
In the two files woocommerce-wirecard-checkout-seamless/classes/class-wirecard-datastorage.php
and woocommerce-wirecard-checkout-seamless/classes/class-wirecard-gateway.php you are using site_url() instead of home_url().

See (y)our fix for the wcp plugin here https://github.com/wirecard/woocommerce-wcp/commit/92ebc038cd59a6770ada5e1fb5bdd02520b2f5b5

**Comment by jakubpolomsky** [comment]
Thank you for your input! We will fix it in the next release. If you cannot wait for the next release feel free to create a pull request fixing this. It is usually much faster and can be processed within hours.

Kind regards
Wirecard

**Comment by tomazpu** [comment]
Thank you for your pull request.

Cheers
