### ISSUE TITLE
Issues at CC Input

### ISSUE THREAD

**Issue by starflower** [wirecard/woocommerce-wcs#71]
We detected several problems:

1) Activate the plugin and leave the setting "SAQ A compliance" on **OFF**:
If you enter an incorrect expiration date (e.g. 02/20 instead of 02/2020, which can happen very easily because on most cards the date is printed short) the input field will still be marked as valid and when sending the checkout form you will get the error on the shopping cart page: _Response failed! Error: No payment information available for this payment method._ 

2) If you activate the plugin and set the setting "SAQ A compliance" to **ON**:
The input fields are marked inline as incorrect if you enter an incorrect expiry date or an incorrect card number ("Invalid credit card number"), but it is still possible to press the order button, whereupon you will receive the following error on the checkout page _Expiration Date invalid_. Immediately afterwards, however, a reload or redirection to the shopping cart page takes place, where the following error can be seen again: _Response failed! Error: No payment information available for this payment method._

In addition, the Checkout Journal logs all errors that are not visible in WooCommerce. (18302 STORAGEID is disabled )

**Comment by jakubpolomsky** [comment]
Hello,

thank you for your contribution!

Ad 1) There is a placeholder defined in the mask. Therefore I don't really understand the issue. Nevertheless I have provided a solution for this "problem"

Ad 2) I could not reproduce the behavior. Could you please provide the exact steps to reproduce this? I can see the errors but I am not forwarded to any site after clicking on the "place order" button and I am still on the same page reading the errors in the iframe and on the top of the checkout page.

Kind regards

**Comment by starflower** [comment]
Nice, thank you! 

Just checked, the EU VAT Number Plugin by WooCommerce is causing this problem and redirecting to the cart after clicking the place order button

https://woocommerce.com/products/eu-vat-number/

**Comment by jakubpolomsky** [comment]
Hello,

Can you provide a fix to that problem (pull-request)? As there are so many third party plugins we cannot assure, that our plugin works with every one of them. I'd be pleased to see your solution and after our review we will be happy to merge it with the next release.

Kind regards!
